# organization name, it's used to get github repo url, also in page title
name: fs-utils

# badge style, can be "flat", "flat-square" or ""
# see http://shields.io/ for details
badge_style: flat-square

# meta headers in html
title:       FS Utilities
description: require('fs') utilities
keywords:

# list of projects, this will be sorted by name;
# every package is either string or object
projects:
 - rimraf-then
 - mkdirp-then
 - name: fs-cp
   repo: fs-utils/cp
 - name: fs-symlink
   repo: fs-utils/symlink
 - file-watch
 - name: fs-reap
   repo: fs-utils/reap
 - name: fs-lru-cache

# list of maintainers, this won't be sorted
maintainers:
 - name:    Jonathan Ong
   github:  jonathanong
   npm:     jongleberry
   twitter: jongleberry
   gittip:  jonathanong
   email:   me@jongleberry.com

   # if gravatar is attached to an email different from specified above,
   # add md5 of it here:
   avatar:  6e33cc0412b61cc01daac23c8989003c

# this determines what info will be fetched with `make db`;
# you can comment out stuff to reduce number of http requests
db.json:
  projects:
   - node        # node version, it's the lowest version from .travis.yml
   - description # package description from package.json (from npm registry)
   - maintainer  # maintainer npm account (= _npmUser of last published ver)
  maintainers:
   - packages    # amount of packages this npm user has
